### ISSUE TITLE
Add conditional npm publish GitHub action

### ISSUE THREAD

**Issue by inigomarquinez** [onebeyond/cuckoojs#59]
If we update cuckoo cli, we can't publish the updates to npm because the GitHub action we have in place publishes the cuckoo schematics first.

However, if the schematics don't have any update, the action fails and it doesn't publish the cli updates.

So we need to modify the GitHub action to publish conditionally. @neodmy has found an action that can be used: https://github.com/marketplace/actions/version-check

**Comment by neodmy** [comment]
Since this approach didn't work, will close this issue in favour of #63
